import AxeBuilder from '@axe-core/playwright';
import { test, expect } from '@playwright/test';
test('edit six slots, prevent duplicates, replace, remove and restore a shared team', async ({ page, context }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const names = ['Pikachu', 'Charizard', 'Venusaur', 'Blastoise', 'Gengar', 'Dragonite'];
  for (const [index, name] of names.entries()) {
    await page.getByRole('button', { name: `Add Pokémon to slot ${index + 1}`, exact: true }).click();
    await page.getByRole('searchbox').fill(name);
    await page.getByRole('button', { name: `Choose ${name}`, exact: true }).click();
    await expect(page.getByTestId(`slot-${index}`).getByRole('heading', { name, exact: true })).toBeVisible();
  }
  await page.getByRole('button', { name: 'Replace Charizard', exact: true }).click();
  await page.getByRole('searchbox').fill('Pikachu');
  await expect(page.getByRole('button', { name: 'Pikachu, already in team', exact: true })).toBeDisabled();
  await page.getByRole('searchbox').fill('Garchomp');
  await page.getByRole('button', { name: 'Choose Garchomp', exact: true }).click();
  await page.getByRole('button', { name: 'Remove Venusaur', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Add Pokémon to slot 3', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Share team', exact: false }).click();
  const link = await page.getByRole('textbox', { name: 'Your team link' }).inputValue();
  const other = await context.newPage();
  await other.goto(link);
  await expect(other.getByTestId('slot-0').getByRole('heading', { name: 'Pikachu', exact: true })).toBeVisible();
  await expect(other.getByTestId('slot-1').getByRole('heading', { name: 'Garchomp', exact: true })).toBeVisible();
  await expect(other.getByRole('button', { name: 'Add Pokémon to slot 3', exact: true })).toBeVisible();
  await expect(other.getByTestId('slot-5').getByRole('heading', { name: 'Dragonite', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Clear team', exact: true }).click();
  await expect(page.getByRole('button', { name: /Add Pokémon to slot/ })).toHaveCount(6);
  expect(errors).toEqual([]);
});
test('search and filters work with keyboard dialog dismissal and no horizontal overflow', async ({ page }) => {
  await page.goto('/');
  const add = page.getByRole('button', { name: 'Add Pokémon to slot 1', exact: true });
  await expect(add).toBeEnabled();
  await add.focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('searchbox')).toBeFocused();
  await page.getByRole('searchbox').fill('#025');
  await expect(page.getByRole('button', { name: 'Choose Pikachu', exact: true })).toBeVisible();
  await page.getByRole('searchbox').fill('');
  await page.getByLabel('Type', { exact: true }).selectOption('Fire');
  await page.getByLabel('Generation', { exact: true }).selectOption('1');
  await expect(page.getByRole('button', { name: 'Choose Charmander', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Choose Pikachu', exact: true })).toHaveCount(0);
  await page.getByRole('searchbox').fill('zzzzzz');
  await expect(page.getByText('No Pokémon match these filters.', { exact: false })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(add).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
test('malformed links repair safely and blocked clipboard has a manual fallback', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { value: { writeText: () => Promise.reject(new Error('blocked')) }, configurable: true }));
  await page.goto('/?v=1&format=unknown&team=pikachu,pikachu,nope');
  await expect(page.getByText('Some invalid or duplicate entries in this link were removed.', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Pikachu', exact: true })).toHaveCount(1);
  await page.getByRole('button', { name: 'Share team', exact: false }).click();
  await expect(page.getByText('Copy the team link below to share your team.', { exact: true })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Your team link' })).toHaveValue(/team=pikachu/);
});
test('analysis updates live and exposes the damage matrix and methodology', async ({ page }) => {
  await page.goto('/?v=1&team=charizard,moltres,hooh');
  await expect(page.getByText('Rock attacks threaten 3 of 3 teammates, with no teammate resisting them by type.', { exact: true })).toBeVisible();
  const before = Number(await page.getByTestId('score-defense').textContent());
  await page.getByRole('button', { name: 'Add Pokémon to slot 4', exact: true }).click();
  await page.getByRole('searchbox').fill('Excadrill');
  await page.getByRole('button', { name: 'Choose Excadrill', exact: true }).click();
  await expect.poll(async () => Number(await page.getByTestId('score-defense').textContent())).toBeGreaterThan(before);
  await page.getByText('Detailed type analysis · all 18 types', { exact: true }).click();
  const rock = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Rock', exact: true }) });
  await expect(rock.getByRole('cell', { name: '4×', exact: true })).toHaveCount(3);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByText('How is the score calculated?', { exact: true }).click();
  await expect(page.getByText('Small teams are provisional', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Clear team', exact: true }).click();
  await expect(page.getByTestId('team-score')).toHaveText('0/ 100');
});
test('recommendations apply the displayed score and target an explicit replacement slot', async ({ page }) => {
  await page.goto('/?v=1&team=charizard,moltres,hooh');
  await expect(page.getByLabel('Slot to optimize', { exact: true })).toHaveValue('3');
  const first = page.getByTestId('recommendation').first();
  await expect(first).toBeVisible();
  const addedId = await first.getAttribute('data-pokemon');
  const expected = await first.getAttribute('data-new-score');
  await first.getByRole('button').click();
  await expect(page.getByTestId('team-score')).toHaveText(`${expected}/ 100`);
  expect(new URL(page.url()).searchParams.get('team')?.split(',')[3]).toBe(addedId);
  await page.getByLabel('Slot to optimize', { exact: true }).selectOption('0');
  await expect(page.getByText('Replacing Charizard in slot 1.', { exact: false })).toBeVisible();
  const replacement = page.getByTestId('recommendation').first();
  const replacementId = await replacement.getAttribute('data-pokemon');
  const replacementScore = await replacement.getAttribute('data-new-score');
  await replacement.getByRole('button').click();
  await expect(page.getByTestId('team-score')).toHaveText(`${replacementScore}/ 100`);
  const ids = new URL(page.url()).searchParams.get('team')?.split(',');
  expect(ids?.[0]).toBe(replacementId); expect(ids?.[1]).toBe('moltres'); expect(ids?.[3]).toBe(addedId);
});
test('SEO routes prefill their Pokémon, honor explicit share state and expose metadata', async ({ page, request }) => {
  await page.goto('/pokemon/garchomp/best-teammates');
  await expect(page.getByTestId('slot-0').getByRole('heading', { name: 'Garchomp', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Garchomp Teammate Suggestions');
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', 'https://superpokemonteambuilder.com/pokemon/garchomp/best-teammates');
  await page.goto('/pokemon/garchomp/best-teammates?v=1&team=pikachu');
  await expect(page.getByTestId('slot-0').getByRole('heading', { name: 'Pikachu', exact: true })).toBeVisible();
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', 'https://superpokemonteambuilder.com/pokemon/garchomp/best-teammates');
  const structured = JSON.parse(await page.locator('script[type="application/ld+json"]').textContent() ?? '{}');
  expect(structured['@type']).toBe('WebApplication');
  await expect(page.locator('meta[property="og:image"]')).toHaveAttribute('content', 'https://superpokemonteambuilder.com/og.png');
  const sitemap = await request.get('/sitemap.xml');
  expect(sitemap.ok()).toBe(true); expect(await sitemap.text()).toContain('/pokemon/garchomp/best-teammates');
  expect(await sitemap.text()).not.toContain('?team=');
  expect(await (await request.get('/robots.txt')).text()).toContain('Sitemap: https://superpokemonteambuilder.com/sitemap.xml');
  expect((await request.get('/og.png')).ok()).toBe(true);
  await page.goto('/weakness-calculator?v=1&team=charizard');
  await expect(page.getByRole('table')).toBeVisible();
});

test('accessible empty, populated and picker states', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Add Pokémon to slot 1', exact: true })).toBeEnabled();
  expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
  await page.goto('/pokemon/garchomp');
  await expect(page.getByTestId('slot-0').getByRole('heading', {name:'Garchomp',exact:true})).toBeVisible();
  expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
  await page.getByRole('button', {name:'Add Pokémon to slot 2',exact:true}).click();
  expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
});
test('unknown routes and unsupported URL versions have safe fallbacks', async ({page}) => {
  const response = await page.goto('/this-page-does-not-exist');
  expect(response?.status()).toBe(404);
  await expect(page.getByRole('heading', {level:1})).toHaveText('That page wandered off.');
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content','noindex, follow');
  await page.goto('/?v=99&team=pikachu');
  await expect(page.getByRole('button', {name:/Add Pokémon to slot/})).toHaveCount(6);
  await expect(page.getByTestId('team-score')).toHaveText('0/ 100');
});
