import { useEffect, useRef, useState } from 'react';
import type { Pokemon } from '../data/pokemon/schema';
// Generated by scripts/generate-sprites.mjs; the 475px source PNGs are never requested at runtime.
const spriteWidth = { small: 160, large: 320 } as const;
export default function PokemonSprite({ pokemon, size = 'small', eager = false }: { pokemon: Pokemon; size?: 'small' | 'large'; eager?: boolean }) {
  const [failed, setFailed] = useState(false);
  const image = useRef<HTMLImageElement>(null);
  useEffect(() => {
    // A prefilled image can fail before React attaches its error handler.
    if (image.current?.complete && image.current.naturalWidth === 0) setFailed(true);
  }, [pokemon.number]);
  const width = spriteWidth[size];
  return <span className={`pokemon-sprite sprite-${size}`} aria-hidden="true">
    {failed ? <span className="sprite-fallback">#{pokemon.number}</span> : <img ref={image} key={pokemon.number} src={`/sprites/official/${width}/${pokemon.number}.webp`} alt="" width={width} height={width} loading={eager ? 'eager' : 'lazy'} decoding="async" onError={() => setFailed(true)}/>}
  </span>;
}
