import { useEffect, useRef, useState } from 'react';
import type { Pokemon } from '../data/pokemon/schema';
// Generated by scripts/generate-sprites.mjs; the 475px source PNGs are never requested at runtime.
const spriteWidth = { small: 160, large: 320 } as const;
export default function PokemonSprite({ pokemon, size = 'small', eager = false }: { pokemon: Pokemon; size?: 'small' | 'large'; eager?: boolean }) {
  const [failed, setFailed] = useState(false);
  const image = useRef<HTMLImageElement>(null);
  useEffect(() => {
    // A prefilled image can fail before React attaches its error handler.
    if (image.current?.complete && image.current.naturalWidth === 0) setFailed(true);
  }, [pokemon.number]);
  const width = spriteWidth[size];
  // Small cards sit at 42–100 CSS pixels, so 160px covers 1x and 2x; 3x phones need the 320px file.
  const src = `/sprites/official/${width}/${pokemon.number}.webp`;
  const srcSet = size === 'small' ? `/sprites/official/160/${pokemon.number}.webp 1x, /sprites/official/320/${pokemon.number}.webp 2x` : undefined;
  return <span className={`pokemon-sprite sprite-${size}`} aria-hidden="true">
    {failed ? <span className="sprite-fallback">#{pokemon.number}</span> : <img ref={image} key={pokemon.number} src={src} srcSet={srcSet} alt="" width={width} height={width} loading={eager ? 'eager' : 'lazy'} decoding="async" onError={() => setFailed(true)}/>}
  </span>;
}
