import { scoringConfig } from '../lib/scoring/config';
import type { Pokemon } from '../data/pokemon/schema';
import type { Analysis } from '../lib/scoring';
export default function TeamAnalysis({ team, analysis, focus = 'all', variant = 'all' }: { variant?: 'all' | 'overview' | 'details'; team: Pokemon[]; analysis: Analysis; focus?: 'all' | 'weakness' | 'coverage' }) {
  const dimensions = [['offense', 'Offense'], ['defense', 'Defense'], ['coverage', 'Coverage'], ['synergy', 'Synergy']] as const;
  return <section className={`analysis analysis-${variant}`} aria-label={variant === 'details' ? 'Detailed team analysis' : undefined} aria-labelledby={variant === 'details' ? undefined : 'analysis-title'}>
    {variant !== 'details' && <div className="analysis-overview"><div className="score-details"><h2 id="analysis-title">Understand your team</h2><div className="dimension-grid">{dimensions.map(([key, label]) => <div className="dimension" key={key}><div><span>{label}</span><strong data-testid={`score-${key}`}>{analysis.scores[key]}</strong></div><meter min="0" max="100" value={analysis.scores[key]} aria-label={`${label} score`}/></div>)}</div><p className="analysis-note">Types & base stats only · Not a win probability.</p></div></div>}
    {variant !== 'overview' && <><details className="insights"><summary>Key insights</summary><ul>{analysis.insights.map(i => <li key={i.text} className={`insight-${i.kind}`}><span className="insight-icon" aria-hidden="true">{i.kind === 'warning' ? '⚠' : i.kind === 'positive' ? '✓' : 'i'}</span><span>{i.text}</span></li>)}</ul></details>
    {!!team.length && <details className="detail-panel" open={focus !== 'all'}><summary>Detailed type analysis · all 18 types</summary><p>Incoming damage assumes typing only. 0× = immune, ½× / ¼× = resistant, 2× / 4× = weak. Resistance counts include immunities.</p><div className="matrix-scroll" role="region" aria-label="Defensive type matrix" tabIndex={0}><table><caption>Incoming damage by attacking type</caption><thead><tr><th scope="col">Attack</th>{team.map(p => <th key={p.id} scope="col">{p.name}</th>)}<th scope="col">Weak</th><th scope="col">Resist</th></tr></thead><tbody>{analysis.defense.map(row => <tr key={row.type}><th scope="row">{row.type}</th>{row.multipliers.map((m,i) => <td className={m > 1 ? 'damage-weak' : m < 1 ? 'damage-resist' : ''} key={team[i].id}>{m === .5 ? '½' : m === .25 ? '¼' : m}×</td>)}<td>{row.weak.length}</td><td>{row.resist.length}</td></tr>)}</tbody></table></div><h3>Offensive type coverage</h3><p>Against single-type targets, using only same-type attacks. This is not coverage against every dual-type species.</p><div className="coverage-grid">{analysis.coverage.map(row => <div key={row.type} className={row.multiplier > 1 ? 'covered' : ''}><span>{row.type}</span><strong>{row.multiplier > 1 ? '✓ Super effective' : row.multiplier === 1 ? 'Neutral' : row.multiplier === 0 ? 'Immune target' : 'Resisted'}</strong></div>)}</div></details>}
    <details className="method-panel"><summary>How is the score calculated?</summary><p>Offense (25%): neutral-or-better type coverage and strongest attacking base stats. Defense (30%): team resistances, unprotected and repeated weaknesses, and 4× vulnerabilities. Coverage (25%): fraction of 18 single-type targets hit super effectively by your own types. Synergy (20%): teammates resisting each other’s weaknesses, physical/special/bulk stat signals and base Speed ≥100. Scores are rounded to 0–100; the total uses the displayed subscores.</p><p>Rating bands: Excellent ≥{scoringConfig.ratings.excellent}, Good ≥{scoringConfig.ratings.good}, Fair ≥{scoringConfig.ratings.fair}, Poor below {scoringConfig.ratings.fair}. An empty team has no rating.</p><p>Small teams are provisional and are not given a separate completion bonus. Adding a Pokémon can lower the score if it creates new weaknesses or lowers averages. These initial heuristics have not been calibrated against battle outcomes.</p></details>
    </>}
  </section>;
}
