import type { Pokemon } from '../data/pokemon/schema';
import type { Analysis } from '../lib/scoring';
export default function TeamAnalysis({ team, analysis }: { team: Pokemon[]; analysis: Analysis }) {
  const dimensions = [['offense', 'Offense'], ['defense', 'Defense'], ['coverage', 'Coverage'], ['synergy', 'Synergy']] as const;
  return <section className="analysis" aria-labelledby="analysis-title">
    <div className="analysis-overview"><div className="score-card"><p className="eyebrow" id="analysis-title">TEAM SCORE</p><div className="score-number" data-testid="team-score">{analysis.total}<span>/ 100</span></div><strong>{analysis.rating}</strong><p>{team.length ? `${team.length}/6 members · ${team.length < 6 ? 'Provisional team' : 'Full team'}` : 'Choose a Pokémon to begin'}</p></div>
      <div className="score-details"><h2>Understand your team</h2><div className="dimension-grid">{dimensions.map(([key, label]) => <div className="dimension" key={key}><div><span>{label}</span><strong data-testid={`score-${key}`}>{analysis.scores[key]}</strong></div><meter min="0" max="100" value={analysis.scores[key]} aria-label={`${label} score`}/></div>)}</div><p className="analysis-note">A type-and-base-stat planning score, not a win probability. Uses your Pokémon’s own types as an estimate of attack coverage. Moves, abilities, items, Terastallization and competitive rules are not modeled.</p></div></div>
    <div className="insights"><h2>Key insights</h2><ul>{analysis.insights.map(i => <li key={i.text} className={`insight-${i.kind}`}><span className="insight-icon" aria-hidden="true">{i.kind === 'warning' ? '⚠' : i.kind === 'positive' ? '✓' : 'i'}</span><span>{i.text}</span></li>)}</ul></div>
    {!!team.length && <details className="detail-panel"><summary>Detailed type analysis · all 18 types</summary><p>Incoming damage assumes typing only. 0× = immune, ½× / ¼× = resistant, 2× / 4× = weak. Resistance counts include immunities.</p><div className="matrix-scroll" role="region" aria-label="Defensive type matrix" tabIndex={0}><table><caption>Incoming damage by attacking type</caption><thead><tr><th scope="col">Attack</th>{team.map(p => <th key={p.id} scope="col">{p.name}</th>)}<th scope="col">Weak</th><th scope="col">Resist</th></tr></thead><tbody>{analysis.defense.map(row => <tr key={row.type}><th scope="row">{row.type}</th>{row.multipliers.map((m,i) => <td className={m > 1 ? 'damage-weak' : m < 1 ? 'damage-resist' : ''} key={team[i].id}>{m === .5 ? '½' : m === .25 ? '¼' : m}×</td>)}<td>{row.weak.length}</td><td>{row.resist.length}</td></tr>)}</tbody></table></div><h3>Offensive type coverage</h3><p>Against single-type targets, using only same-type attacks. This is not coverage against every dual-type species.</p><div className="coverage-grid">{analysis.coverage.map(row => <div key={row.type} className={row.multiplier > 1 ? 'covered' : ''}><span>{row.type}</span><strong>{row.multiplier > 1 ? '✓ Super effective' : row.multiplier === 1 ? 'Neutral' : row.multiplier === 0 ? 'Immune target' : 'Resisted'}</strong></div>)}</div></details>}
    <details className="method-panel"><summary>How is the score calculated?</summary><p>Offense (25%): neutral-or-better type coverage and strongest attacking base stats. Defense (30%): team resistances, unprotected and repeated weaknesses, and 4× vulnerabilities. Coverage (25%): fraction of 18 single-type targets hit super effectively by your own types. Synergy (20%): teammates resisting each other’s weaknesses, physical/special/bulk stat signals and base Speed ≥100. Scores are rounded to 0–100; the total uses the displayed subscores.</p><p>Small teams are provisional and are not given a separate completion bonus. Adding a Pokémon can lower the score if it creates new weaknesses or lowers averages. These initial heuristics have not been calibrated against battle outcomes.</p></details>
  </section>;
}
